[package]
# Basic package information
name = "kernel"       # The name of the kernel package/project
version = "0.1.0"           # The current version of the project
edition = "2024"            # The Rust edition being used (2024 edition)
build = "src/build.rs"      # Specifies a custom build script located at "src/build.rs"

[dependencies]
# Core dependencies for the kernel
linked_list_allocator = "0.10.4" # Provides a linked list allocator for dynamic memory allocation


[build-dependencies]
# Build script dependencies
cc = "1.0"                  # Enables building and linking C code during the build process

[[bin]]
name = "kernel"
path = "src/main.rs"