name: Format Code

on:
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  rustfmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Set nightly as default
        run: rustup default nightly

      - name: Format code
        run: cargo fmt
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m 'Format code with rustfmt'
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORK_BOT }}
